# Generated by Django 5.1.7 on 2025-04-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0002_alter_unidad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidad',
            options={'ordering': ['cod_unidad'], 'verbose_name': 'Unidad', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.AddField(
            model_name='unidad',
            name='cod_unidad',
            field=models.CharField(default=1, help_text='Código jerárquico de la unidad', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
