# Generated by Django 5.1.7 on 2025-04-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0003_alter_unidad_options_unidad_cod_unidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidad',
            options={'ordering': ['nivel', 'orden', 'cod_unidad'], 'verbose_name': 'Unidad', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.AddField(
            model_name='unidad',
            name='nivel',
            field=models.IntegerField(default=1, help_text='Nivel jerárquico (calculado automáticamente)'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='orden',
            field=models.IntegerField(default=1, help_text='Orden dentro de su nivel y padre'),
        ),
    ]
