# Generated by Django 5.1.7 on 2025-04-03 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0004_alter_unidad_options_unidad_nivel_unidad_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidad',
            options={'ordering': ['nivel', 'cod_unidad'], 'verbose_name': 'Unidad', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='orden',
        ),
        migrations.AlterField(
            model_name='unidad',
            name='cod_unidad',
            field=models.CharField(help_text='Código jerárquico correlativo', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='id_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subunidades', to='unidades.unidad'),
        ),
    ]
