# Generated by Django 5.1.7 on 2025-04-08 07:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0005_alter_unidad_options_remove_unidad_orden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidad',
            name='tipo_unidad',
            field=models.CharField(choices=[('DIRECCION', 'Dirección General'), ('ZONA', 'Zona'), ('COMANDANCIA', 'Comandancia'), ('COMPANIA', 'Compañía'), ('PUESTO', 'Puesto')], default='PUESTO', help_text='Tipo/categoría de la unidad', max_length=15),
        ),
    ]
