# Generated by Django 5.1.7 on 2025-04-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0006_unidad_descripcion_unidad_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='tipo_unidad',
            field=models.CharField(choices=[('DIRECCION', 'Dirección General'), ('ZONA', 'Zona'), ('COMANDANCIA', 'Comandancia'), ('ZONA_COMANDANCIA', 'Zona-Comandancia'), ('COMPANIA', 'Compañía'), ('PUESTO', 'Puesto')], default='PUESTO', help_text='Tipo/categoría de la unidad', max_length=30),
        ),
    ]
