# Generated by Django 5.1.7 on 2025-03-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usuario_empleo_remove_unidad_id_padre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('SuperAdmin', 'Super Administrador'), ('Admin', 'Administrador'), ('Gestor', 'Gestor'), ('User', 'Usuario')], default='User', max_length=15),
        ),
    ]
