# Generated by Django 5.1.7 on 2025-04-08 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0007_unidad_descripcion_unidad_fecha_actualizacion_and_more'),
        ('users', '0005_usuario_unidad_acceso_usuario_unidad_destino_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='unidad',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='unidad_destino',
            field=models.ForeignKey(blank=True, help_text='Unidad a la que el usuario está destinado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_destinados', to='unidades.unidad'),
        ),
    ]
