# Generated by Django 5.1.7 on 2025-03-20 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('url', models.URLField(blank=True, help_text='URL externa si el documento no está alojado en el sistema', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Procedimiento',
                'verbose_name_plural': 'Tipos de Procedimientos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('VIGENTE', 'Vigente'), ('OBSOLETO', 'Obsoleto')], default='BORRADOR', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedimientos_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedimientos_creados', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos', to='procedimientos.tipoprocedimiento')),
            ],
            options={
                'verbose_name': 'Procedimiento',
                'verbose_name_plural': 'Procedimientos',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='Paso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tiempo_estimado', models.CharField(blank=True, help_text="Ejemplo: '30 minutos', '2 horas'", max_length=50, null=True)),
                ('responsable', models.CharField(blank=True, help_text='Cargo o rol responsable de ejecutar este paso', max_length=100, null=True)),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='procedimientos.procedimiento')),
            ],
            options={
                'verbose_name': 'Paso',
                'verbose_name_plural': 'Pasos',
                'ordering': ['procedimiento', 'numero'],
                'unique_together': {('procedimiento', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='HistorialProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('descripcion_cambio', models.TextField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='procedimientos.procedimiento')),
            ],
            options={
                'verbose_name': 'Historial de Procedimiento',
                'verbose_name_plural': 'Historial de Procedimientos',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoPaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre este documento en el contexto de este paso', null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='procedimientos.documento')),
                ('paso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='procedimientos.paso')),
            ],
            options={
                'verbose_name': 'Documento de Paso',
                'verbose_name_plural': 'Documentos de Pasos',
                'ordering': ['paso', 'orden'],
                'unique_together': {('paso', 'documento')},
            },
        ),
    ]
