# Generated by Django 5.1.7 on 2025-03-25 07:10

import django.db.models.deletion
import procedimientos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='procedimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='procedimientos.procedimiento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=procedimientos.models.documento_upload_path),
        ),
    ]
