# Generated by Django 5.1.7 on 2025-03-25 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0002_documento_procedimiento_alter_documento_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='documento',
            name='procedimiento',
            field=models.ForeignKey(blank=True, help_text='Procedimiento al que pertenece este documento (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_directos', to='procedimientos.procedimiento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL externa'),
        ),
    ]
