# Generated by Django 5.1.7 on 2025-03-26 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0003_alter_documento_nombre_alter_documento_procedimiento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-fecha_actualizacion'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterModelOptions(
            name='paso',
            options={'ordering': ['numero'], 'verbose_name': 'Paso', 'verbose_name_plural': 'Pasos'},
        ),
        migrations.AddField(
            model_name='paso',
            name='bifurcaciones',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='documento',
            name='procedimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='procedimientos.procedimiento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paso',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paso',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paso',
            name='tiempo_estimado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
