# Generated by Django 5.1.7 on 2025-04-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0004_alter_documento_options_alter_paso_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimiento',
            name='nivel',
            field=models.CharField(choices=[('PUESTO', 'Puesto'), ('COMPANIA', 'Compañía'), ('COMANDANCIA', 'Comandancia'), ('ZONA', 'Zona'), ('DIRECCION', 'Dirección General'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='procedimiento',
            unique_together={('nombre', 'tipo', 'nivel')},
        ),
    ]
