# Generated by Django 5.1.7 on 2025-04-07 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0005_procedimiento_nivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimiento',
            name='procedimiento_relacionado',
            field=models.ForeignKey(blank=True, help_text='Procedimiento de nivel superior al que se envía este procedimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedimientos_derivados', to='procedimientos.procedimiento'),
        ),
    ]
