# Generated by Django 5.1.7 on 2025-04-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0006_procedimiento_procedimiento_relacionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='paso',
            name='es_final',
            field=models.BooleanField(default=False, help_text='Indica si este paso finaliza el procedimiento'),
        ),
    ]
