# Generated by Django 5.1.7 on 2025-04-07 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0007_paso_es_final'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='documentopaso',
            options={'ordering': ['orden'], 'verbose_name': 'Documento de paso', 'verbose_name_plural': 'Documentos de pasos'},
        ),
        migrations.AddField(
            model_name='documento',
            name='extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='documento',
            name='procedimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='procedimientos.procedimiento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='documentopaso',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedimientos.documento'),
        ),
        migrations.AlterField(
            model_name='documentopaso',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentopaso',
            name='orden',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='documentopaso',
            name='paso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documento_paso', to='procedimientos.paso'),
        ),
    ]
