# Generated by Django 5.1.7 on 2025-04-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0008_alter_documento_options_alter_documentopaso_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimiento',
            name='tiempo_maximo',
            field=models.PositiveIntegerField(blank=True, help_text='Número de días máximo para completar el procedimiento', null=True),
        ),
    ]
