# Generated by Django 5.1.7 on 2025-04-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0009_procedimiento_tiempo_maximo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paso',
            name='requiere_envio',
            field=models.BooleanField(default=False, help_text='Indica si este paso requiere un envío que necesita respuesta para continuar'),
        ),
    ]
