# Generated by Django 5.1.7 on 2025-04-22 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0010_add_requiere_envio_to_paso'),
        ('unidades', '0007_unidad_descripcion_unidad_fecha_actualizacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADO', 'Completado'), ('BLOQUEADO', 'Bloqueado')], default='PENDIENTE', max_length=20)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('bifurcacion_elegida', models.IntegerField(blank=True, null=True)),
                ('paso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instancias_trabajo', to='procedimientos.paso')),
                ('usuario_completado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasos_completados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paso de Trabajo',
                'verbose_name_plural': 'Pasos de Trabajo',
                'ordering': ['paso__numero'],
            },
        ),
        migrations.CreateModel(
            name='EnvioPaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_salida', models.CharField(max_length=100)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('documentacion', models.FileField(upload_to='procedimientos/envios/%Y/%m/')),
                ('notas_adicionales', models.TextField(blank=True, null=True)),
                ('paso_trabajo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='envio', to='procedimientos.pasotrabajo')),
            ],
            options={
                'verbose_name': 'Envío de Paso',
                'verbose_name_plural': 'Envíos de Pasos',
            },
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('INICIADO', 'Iniciado'), ('EN_PROGRESO', 'En progreso'), ('PAUSADO', 'Pausado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='INICIADO', max_length=20)),
                ('paso_actual', models.PositiveIntegerField(default=1)),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos', to='procedimientos.procedimiento')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos', to='unidades.unidad')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='pasotrabajo',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos_trabajo', to='procedimientos.trabajo'),
        ),
    ]
