# Generated by Django 5.1.7 on 2025-04-23 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0011_pasotrabajo_enviopaso_trabajo_pasotrabajo_trabajo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='usuario_iniciado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_iniciados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='usuario_creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
