# Generated by Django 5.1.7 on 2025-04-24 07:46

import procedimientos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0012_trabajo_usuario_iniciado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasotrabajo',
            name='paso_numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enviopaso',
            name='documentacion',
            field=models.FileField(upload_to=procedimientos.models.envio_upload_path),
        ),
    ]
