# Generated by Django 5.1.7 on 2025-04-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0013_pasotrabajo_paso_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paso',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paso',
            name='numero',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='paso',
            name='tiempo_estimado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
