# Generated by Django 5.1.7 on 2025-04-24 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0014_alter_paso_descripcion_alter_paso_numero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasotrabajo',
            name='paso_numero',
        ),
    ]
