# Generated by Django 5.1.7 on 2025-04-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0015_remove_pasotrabajo_paso_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='tipo_documento',
            field=models.CharField(choices=[('GENERAL', 'Documento general'), ('PASO', 'Documento asociado a paso')], default='GENERAL', help_text='Indica si el documento es general del procedimiento o está asociado a un paso específico', max_length=10),
        ),
    ]
